version: "3.7"
services:
  licensing-service:
    image: licensing-service:v1
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    networks:
      backend:
        aliases:
          - "licenseservice"

networks:
  backend:
    driver: bridge