management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /
  health:
    db:
      enabled: false
    diskspace:
      enabled: true
  endpoint:
    health:
      enabled: true
      show-details: always
